### ISSUE TITLE
Getting a scale factor with imaginary part when working with GABDUALNORM

### ISSUE THREAD

**Issue by rajmic** [ltfat/ltfat#137] opened 2022-05-11 09:42 UTC
Hello,
for specific window settings, I get the scal factor containing a tiny imaginary part, which I consider weird. (And it ruins subsequent processing when it comes to the final synthesis.) Could you explain if I am doing something wrong? If it is a non-solvable problem, how should we cope with it? Take the real part only or the magnitude?

Here is the code which is ok:
winLen = 27;
synthesisWindow = fftshift(firwin('hann',winLen));
analysisWindow = ones(winLen,1);
hopSize = winLen/3;
[scal,residual] = gabdualnorm(analysisWindow,synthesisWindow,hopSize,winLen)

But once I switch to a higher window length, the imaginary component appears:
winLen = 501;
synthesisWindow = fftshift(firwin('hann',winLen));
analysisWindow = ones(winLen,1);
hopSize = winLen/3;
[scal,residual] = gabdualnorm(analysisWindow,synthesisWindow,hopSize,winLen)

Thank you very much.
regards, Pavel

**Comment by nholighaus** [comment] 2022-05-12 08:11
Dear Pavel,
looking into the code, the complex part is just numerical garbage,
caused by the dgt algorithm. If both your candidate windows
(analysisWindow and synthesisWindow in your test code) are real-valued,
you can safely take the real part of the first output argument, which
should simply be the inner product of the two windows.

On the other hand, I am not happy about how the second output is
computed, which I believe would be more appropriate if also scaled like
the first output, i.e., changing l.128 from 'o2=norm(rhs(2:end),1);' to
'  o2=norm(rhs(2:end),1)/scalconst;'.

This is sort of suggested by the help, which states: '*res* is close to
zero if the windows (scaled correctly) are dual windows.' I would think
that making M/a unreasonably large, 'res' might not be close to zero
anymore. I also think it would be more helpful to provide a value that
describes the deviation from duality if the windows were scaled
correctly. Maybe someone can chime in. Since this would break
compatibility, it's not a change that would be in the next minor release
anyway.

I further find it slightly confusing to refer to the first parameter as
a 'scaling', which may suggest that it should always be a positive
number, when it can (depending on the choices of window) be any nonzero
complex number. I do, however, accept that one can disagree on this. It
might still be helpful to add a note in the help, which I'll do right away.

Best,
Nicki

**Comment by nholighaus** [comment] 2022-05-12 08:31
I uploaded my changes. In particular, for strictly real-valued input windows, 'scal' is always restricted to be real. This closes the original issue. If no one disagrees, I will close the issue and open a new one to discuss the convention change for the second output later today.

**Comment by rajmic** [comment] 2022-05-12 15:18
Thank you for solving my issue!

Regarding the follow-up questions and suggestions, I appreciate your precise way of thinking and I agree with your argumentation.

On the other hand, for instance the phrase 'close to zero' would still be applicable even in your extreme example, since noone  gives (and cannot give) particular limits what is 'large enough'... :)

Best, Pavel

**Closed** 2022-05-24 08:22 UTC
